import os
from graph import LegalDocumentAgent, AgentState

# Set the provided OpenRouter API key
test_api_key = "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"

# Initialize the agent with the API key
agent = LegalDocumentAgent(api_key=test_api_key)

# Create a test NDA state
state = AgentState(
    session_id="test-session",
    user_input="I need an NDA between Alice and Bob",
    document_type="nda",
    collected_info={
        "disclosing_party": "Alice",
        "receiving_party": "Bob",
        "purpose": "Discussing a business idea",
        "duration": "2 years",
        "jurisdiction": "California"
    },
    is_complete=True
)
state_dict = state.model_dump() if hasattr(state, "model_dump") else state.dict()

# Generate the document
result = agent.generate_document(state_dict)
document = result.get("final_document", "[No document generated]")
error_message = result.get("error_message", "")

print("\n=== LLM Document Generation Test ===\n")
if error_message:
    print(f"Error: {error_message}")
elif "[Generated by LLM" in document:
    print("LLM Output:\n")
    print(document.replace("\n\n[Generated by LLM (OpenRouter DeepSeek)]", "").strip())
else:
    print("No LLM output. The document was not generated by the LLM. Check your API key or try again later.") 